// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, b, c, check, fs, g, generator, make_generator, seem;

  check = (require('assert')).deepEqual;

  Promise = require('bluebird');

  fs = Promise.promisifyAll(require('fs'));

  make_generator = function*(x) {
    var a;
    check(x, 4);
    a = (yield x + 3);
    check(a, 9);
    return null;
  };

  generator = make_generator(4);

  b = generator.next(8);

  check(b.value, 7);

  check(b.done, false);

  c = generator.next(9);

  check(c.value, null);

  check(c.done, true);

  seem = require('../index');

  make_generator = function*(x) {
    var a;
    a = parseInt((yield fs.readFileAsync(x)));
    check(a, 4);
    b = parseInt((yield fs.readFileAsync('3plus' + a)));
    check(b, 7);
    return fs.readFileAsync('bar' + b, {
      encoding: 'utf-8'
    });
  };

  g = seem(make_generator);

  b = g('four');

  b.then(function(x) {
    return check(x, 'foo\n');
  });

}).call(this);
